export default {
  products: [
    {
      image: "/images/d1.jpeg",
      name: "slim short",
      price: "80",
      brand: "nake",
      rating: "10",
      _id: "1",
      numReviews: 10,
      countInStock: 5,
    },
    {
      image: "/images/d10.jpeg",
      name: "slim short",
      price: "840",
      brand: "d3",
      rating: "10",
      _id: "2",
      numReviews: 10,
      countInStock: 4,
    },
    {
      image: "/images/d9.jpeg",
      name: "slim short",
      price: "280",
      brand: "nike",
      rating: "10",
      _id: "3",
      numReviews: 10,
      countInStock: 12,
    },
    {
      image: "/images/d8.jpeg",
      name: "slim short",
      price: "830",
      brand: "applee",
      rating: "10",
      _id: "4",
      numReviews: 10,
      countInStock: 8,
    },
    {
      image: "/images/d7.jpeg",
      name: "slim short",
      price: "30",
      brand: "puma 2020",
      rating: "10",
      _id: "5",
      numReviews: 10,
      countInStock: 10,
    },
    {
      image: "/images/d6.jpeg",
      name: "slim short",
      price: "800",
      brand: "nike air",
      rating: "10",
      id: "6",
      numReviews: 10,
      countInStock: 2,
    },
    {
      image: "/images/d5.jpeg",
      name: "slim short",
      price: "400",
      brand: "samsung",
      rating: "10",
      _id: "7",
      numReviews: 10,
      countInStock: 4,
    },
    {
      image: "/images/d4.jpeg",
      name: "slim short",
      price: "120",
      brand: "calvin clain",
      rating: "10",
      _id: "8",
      numReviews: 10,
      countInStock: 8,
    },
    {
      image: "/images/d3.jpeg",
      name: "slim short",
      price: "20",
      brand: "puma",
      rating: "10",
      _id: "9",
      numReviews: 10,
      countInStock: 6,
    },
    {
      image: "/images/d2.jpeg",
      name: "slim short",
      price: "40",
      brand: "adiddas",
      rating: "10",
      _id: "10",
      numReviews: 10,
      countInStock: 0,
    },
  ],
};
